const profileVideoDB = [
    {
        "user_id":999,
        "user_name":"PRIME_WAIYAN",
        "user_profile":"https://scontent.frgn4-1.fna.fbcdn.net/v/t39.30808-6/331983456_772736064272486_6062597388829844809_n.jpg?stp=cp6_dst-jpg&_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=dVmbGvZ98IIAX_JMwIK&_nc_ht=scontent.frgn4-1.fna&oh=00_AfCIPeeVCf-WWiRiYdBLHv-zYQdF2hZQQGALEahQ0_93rQ&oe=6413C483",
        "video_title":"What's happened's happened",
        "video_link":require("./src/assets/videos/video12.mp4"),
        "video_id":12,
        "like":6666666,
        "comment":[],
        "share":666666,
        "size":'contain',
        "type":"post",
    },
    {
        "user_id":101,
        "user_name":"imdb",
        "user_profile":"https://ia.media-imdb.com/images/M/MV5BODc4MTA3NjkzNl5BMl5BcG5nXkFtZTgwMDg0MzQ2OTE@._V1_.png",
        "video_title":"The Beauty of Christopher Nolan",
        "video_link":require("./src/assets/videos/video19.mp4"),
        "video_id":19,
        "like":40000,
        "comment":[],
        "share":26000,
        "size":'contain',
        "type":"liked",
    },
    {
        "user_id":1,
        "user_name":"benjamin",
        "user_profile":"https://flxt.tmsimg.com/assets/487714_v9_bb.jpg",
        "video_title":"Every developer can relate",
        "video_link":require('./src/assets/videos/video02.mp4'),
        "video_id":1,
        "like":999,
        "comment":[],
        "share":678,
        "size":'stretch',
        "type":"share",
    },
    {
        "user_id":2,
        "user_name":"neil_robert",
        "user_profile":"https://i.pinimg.com/originals/db/fe/89/dbfe8969d0ff5100cae8960955ce7b05.jpg",
        "video_title":"You will never ever need to go school again #education",
        "video_link": require("./src/assets/videos/video06.mp4"),
        "video_id":2,
        "like":309,
        "comment":[],
        "share":122,
        "size":'stretch',
        "type":"share",
    },
     
    {
        "user_id":101,
        "user_name":"imdb",
        "user_profile":"https://ia.media-imdb.com/images/M/MV5BODc4MTA3NjkzNl5BMl5BcG5nXkFtZTgwMDg0MzQ2OTE@._V1_.png",
        "video_title":"Top 5 Christopher Nolan's Movie",
        "video_link":require("./src/assets/videos/video16.mp4"),
        "video_id":16,
        "like":100004,
        "comment":[],
        "share":8888,
        "size":'stretch',
        "type":"liked",
    },   
    {
        "user_id":4,
        "user_name":"harry_styles",    
        "user_profile":"https://flxt.tmsimg.com/assets/487714_v9_bb.jpg",
        "video_title":"Lonely nights hehehehehehheh hehehehe ehheheheeheh T-T #pinkpanther lonely no_girlfriend sad_panther texttttttttttt textttt text",
        "video_link":require("./src/assets/videos/video01.mp4"),
        "video_id":4,
        "like":899,
        "comment":[],
        "share":678,
        "size":'contain',
        "type":"share",
    },     
    {
        "user_id":1,
        "user_name":"benjamin",
        "user_profile":"https://static01.nyt.com/images/2022/05/21/arts/20STYLES-REVIEW1/20STYLES-REVIEW1-mediumSquareAt3X.jpg",
        "video_title":"The Greatests",
        "video_link":require("./src/assets/videos/video05.mp4"),
        "video_id":5,
        "like":1999,
        "comment":[],
        "share":999,
        "size":'stretch',
        "type":"share",
    },        
    {
        "user_id":4,
        "user_name":"harry_styles",
        "user_profile":"https://static01.nyt.com/images/2022/05/21/arts/20STYLES-REVIEW1/20STYLES-REVIEW1-mediumSquareAt3X.jpg",
        "video_title":"This is how I am actually used to code",
        "video_link":require("./src/assets/videos/video03.mp4"),
        "video_id":6,
        "like":999,
        "comment":[],
        "share":678,
        "size":'stretch',
        "type":"share",
    },  
      
    {
        "user_id":999,
        "user_name":"PRIME_WAIYAN",
        "user_profile":"https://scontent.frgn4-1.fna.fbcdn.net/v/t39.30808-6/331983456_772736064272486_6062597388829844809_n.jpg?stp=cp6_dst-jpg&_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=dVmbGvZ98IIAX_JMwIK&_nc_ht=scontent.frgn4-1.fna&oh=00_AfCIPeeVCf-WWiRiYdBLHv-zYQdF2hZQQGALEahQ0_93rQ&oe=6413C483",
        "video_title":"Can't stop falling in love with you",
        "video_link":require("./src/assets/videos/video09.mp4"),
        "video_id":9,
        "like":454,
        "comment":[],
        "share":45,
        "size":'contain',
        "type":"post",
    },  
    {
        "user_id":999,
        "user_name":"PRIME_WAIYAN",
        "user_profile":"https://scontent.frgn4-1.fna.fbcdn.net/v/t39.30808-6/331983456_772736064272486_6062597388829844809_n.jpg?stp=cp6_dst-jpg&_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=dVmbGvZ98IIAX_JMwIK&_nc_ht=scontent.frgn4-1.fna&oh=00_AfCIPeeVCf-WWiRiYdBLHv-zYQdF2hZQQGALEahQ0_93rQ&oe=6413C483",
        "video_title":"Vengeance for everyone, baby for you",
        "video_link":require("./src/assets/videos/video10.mp4"),
        "video_id":10,
        "like":1111,
        "comment":[],
        "share":666,
        "size":'stretch',
        "type":"post",
    },  
    {
        "user_id":999,
        "user_name":"PRIME_WAIYAN",
        "user_profile":"https://scontent.frgn4-1.fna.fbcdn.net/v/t39.30808-6/331983456_772736064272486_6062597388829844809_n.jpg?stp=cp6_dst-jpg&_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=dVmbGvZ98IIAX_JMwIK&_nc_ht=scontent.frgn4-1.fna&oh=00_AfCIPeeVCf-WWiRiYdBLHv-zYQdF2hZQQGALEahQ0_93rQ&oe=6413C483",
        "video_title":"Batman being Batman",
        "video_link":require("./src/assets/videos/video11.mp4"),
        "video_id":11,
        "like":6666666,
        "comment":[],
        "share":666666,
        "size":'stretch',
        "type":"post",
    },
    {
        "user_id":3,
        "user_name":"dior_robert",
        "user_profile":"https://media.wonderlandmagazine.com/uploads/2022/11/Dior-Men-Spring-2023-Campaign-%C2%A9-Rafael-Pavarotti9-scaled.jpg",
        "video_title":"Life keys",
        "video_link":require("./src/assets/videos/video04.mp4"),
        "video_id":3,
        "like":999,
        "comment":[],
        "share":678,
        "size":'stretch',
        "type":"share",
    }, 
    {
        "user_id":101,
        "user_name":"imdb",
        "user_profile":"https://ia.media-imdb.com/images/M/MV5BODc4MTA3NjkzNl5BMl5BcG5nXkFtZTgwMDg0MzQ2OTE@._V1_.png",
        "video_title":"Top 5 Brad Pitt's Movie",
        "video_link":require("./src/assets/videos/video18.mp4"),
        "video_id":18,
        "like":40000,
        "comment":[],
        "share":10000,
        "size":'stretch',
        "type":"liked",
    }, 
     
    
    {
        "user_id":45,
        "user_name":"unknown_british",
        "user_profile":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Great_Britain_%281707%E2%80%931800%29.svg/1200px-Flag_of_Great_Britain_%281707%E2%80%931800%29.svg.png",
        "video_title":"New Prime Minister",
        "video_link":require("./src/assets/videos/video13.mp4"),
        "video_id":13,
        "like":1234,
        "comment":[],
        "share":232,
        "size":'stretch',
        "type":"liked",
    },
    {
        "user_id":999,
        "user_name":"PRIME_WAIYAN",
        "user_profile":"https://scontent.frgn4-1.fna.fbcdn.net/v/t39.30808-6/331983456_772736064272486_6062597388829844809_n.jpg?stp=cp6_dst-jpg&_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=dVmbGvZ98IIAX_JMwIK&_nc_ht=scontent.frgn4-1.fna&oh=00_AfCIPeeVCf-WWiRiYdBLHv-zYQdF2hZQQGALEahQ0_93rQ&oe=6413C483",
        "video_title":"Starboy B",
        "video_link":require("./src/assets/videos/video08.mp4"),
        "video_id":8,
        "like":123,
        "comment":[],
        "share":41,
        "size":'stretch',
        "type":"post",
    },
    {
        "user_id":911,
        "user_name":"general",
        "user_profile":"https://images.fineartamerica.com/images-medium-large-5/french-military-general-cartoon-aloysius-patrimonio.jpg",
        "video_title":"WW-II",
        "video_link":require("./src/assets/videos/video14.mp4"),
        "video_id":14,
        "like":14,
        "comment":[],
        "share":1,
        "size":'stretch',
        "type":"liked",
    },
    {
        "user_id":999,
        "user_name":"PRIME_WAIYAN",
        "user_profile":"https://scontent.frgn4-1.fna.fbcdn.net/v/t39.30808-6/331983456_772736064272486_6062597388829844809_n.jpg?stp=cp6_dst-jpg&_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=dVmbGvZ98IIAX_JMwIK&_nc_ht=scontent.frgn4-1.fna&oh=00_AfCIPeeVCf-WWiRiYdBLHv-zYQdF2hZQQGALEahQ0_93rQ&oe=6413C483",
        "video_title":"Neil is the coolest",
        "video_link":require("./src/assets/videos/video15.mp4"),
        "video_id":15,
        "like":6666666,
        "comment":[],
        "share":666666,
        "size":'stretch',
        "type":"post",
    },  
    {
        "user_id":999,
        "user_name":"PRIME_WAIYAN",
        "user_profile":"https://scontent.frgn4-1.fna.fbcdn.net/v/t39.30808-6/331983456_772736064272486_6062597388829844809_n.jpg?stp=cp6_dst-jpg&_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=dVmbGvZ98IIAX_JMwIK&_nc_ht=scontent.frgn4-1.fna&oh=00_AfCIPeeVCf-WWiRiYdBLHv-zYQdF2hZQQGALEahQ0_93rQ&oe=6413C483",
        "video_title":"Us To gether, nothing is better",
        "video_link":require("./src/assets/videos/video07.mp4"),
        "video_id":7,
        "like":9999999,
        "comment":[],
        "share":999999,
        "size":'stretch',
        "type":"post",
    },  
    {
        "user_id":101,
        "user_name":"imdb",
        "user_profile":"https://ia.media-imdb.com/images/M/MV5BODc4MTA3NjkzNl5BMl5BcG5nXkFtZTgwMDg0MzQ2OTE@._V1_.png",
        "video_title":"Clip from the wolf of wallstreet",
        "video_link":require("./src/assets/videos/video17.mp4"),
        "video_id":17,
        "like":14212,
        "comment":[],
        "share":11323,
        "size":'stretch',
        "type":"liked",
    },
    
   
    

]
export default profileVideoDB;